config/routes.rb
Osem::Application.routes.draw do

  if CONFIG['authentication']['ichain']['enabled']
    devise_for :users, controllers: { registrations: :registrations }
  else
    devise_for :users,
               controllers: {
                   registrations: :registrations, confirmations: :confirmations,
                   omniauth_callbacks: 'users/omniauth_callbacks' },
               path: 'accounts'
  end

  # Use letter_opener_web to open mails in browser (e.g. necessary for Vagrant)
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :users, except: [:new, :index, :create, :destroy]

  namespace :admin do
    resources :users
    resources :people
    resources :comments, only: [:index]
    resources :conference do
      resource :contact, except: [:index, :new, :create, :show, :destroy]
      resources :photos, except: [:show]
      resource :schedule, only: [:show, :update]
      get 'commercials/render_commercial' => 'commercials#render_commercial'
      resources :commercials, only: [:index, :create, :update, :destroy]
      get '/dietary_choices' => 'dietchoices#show', as: 'dietary_list'
      patch '/dietary_choices' => 'dietchoices#update', as: 'dietary_update'
      get '/volunteers_list' => 'volunteers#show'
      get '/volunteers' => 'volunteers#index', as: 'volunteers_info'
      patch '/volunteers' => 'volunteers#update', as: 'volunteers_update'

      resources :registrations, except: [:create, :new] do
        member do
          patch :toggle_attendance

        end
      end

      # Singletons
      resource :splashpage
      resource :venue do
        resources :rooms, except: [:show]
      end
      resource :registration_period
      resource :program do
        resource :cfp
        resources :tracks
        resources :event_types
        resources :difficulty_levels
        resources :events do
          member do
            post :comment
            patch :accept
            patch :confirm
            patch :cancel
            patch :reject
            patch :unconfirm
            patch :restart
            get :vote
          end
          resource :speaker, only: [:edit, :update]
        end
      end

      resources :tickets
      resources :sponsors, except: [:show]
      resources :lodgings, except: [:show]
      resources :targets, except: [:show]
      resources :campaigns, except: [:show]
      resources :emails, only: [:show, :update, :index]
      resources :roles, except: [ :new, :create ] do
        member do
          post :toggle_user
        end
      end

      resources :sponsorship_levels, except: [:show] do
        member do
          patch :up
          patch :down
        end
      end

      resources :questions do
        collection do
          patch :update_conference
        end
      end
    end
  end

  resources :conference, only: [:index, :show] do
    resource :program, except: :destroy do
      resources :proposal do
        get 'commercials/render_commercial' => 'commercials#render_commercial'
        resources :commercials, only: [:create, :update, :destroy]
        resources :event_attachment, controller: 'event_attachments'
        member do
          patch '/confirm' => 'proposal#confirm'
          patch '/restart' => 'proposal#restart'
        end
      end
    end

    resource :conference_registrations, path: 'register'
    resources :tickets, only: [:index]
    resources :ticket_purchases, only: [:create, :destroy]
    resource :subscriptions, only: [:create, :destroy]

    member do
      get :schedule
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :conferences, only: [ :index, :show ] do
        resources :rooms, only: :index
        resources :tracks, only: :index
        resources :speakers, only: :index
        resources :events, only: :index
      end
      resources :rooms, only: :index
      resources :tracks, only: :index
      resources :speakers, only: :index
      resources :events, only: :index
    end
  end

  get '/admin' => redirect('/admin/conference')

  root to: 'conference#index', via: [:get, :options]
end

app/models/ahoy/event.rb
module Ahoy
  class Event < ActiveRecord::Base
    self.table_name = 'ahoy_events'

    belongs_to :visit
    belongs_to :user

    serialize :properties, JSON
  end
end

app/models/event_type.rb
class EventType < ActiveRecord::Base
  belongs_to :program
  has_many :events, dependent: :restrict_with_error

  validates :title, presence: true
  validates :length, numericality: {greater_than: 0}
  validates :minimum_abstract_length, presence: true
  validates :maximum_abstract_length, presence: true

  alias_attribute :name, :title
end

app/controllers/admin/events_controller.rb
module Admin
  class EventsController < Admin::BaseController
    load_and_authorize_resource :conference, find_by: :short_title
    load_and_authorize_resource :program, through: :conference, singleton: true
    load_and_authorize_resource :event, through: :program

    before_action :get_event, except: [:index, :create]

    # FIXME: The timezome should only be applied on output, otherwise
    # you get lost in timezone conversions...
    # around_filter :set_timezone_for_this_request

    def set_timezone_for_this_request(&block)
      Time.use_zone(@conference.timezone, &block)
    end

    def index
      @events = @program.events
      @tracks = @program.tracks
      @difficulty_levels = @program.difficulty_levels
      @machine_states = @events.state_machine.states.map
      @event_types = @program.event_types

      @mystates = []
      @mytypes = []
      @eventstats = {}
      @totallength = 0

      @machine_states.each do |mystate|
        length = 0
        events_mystate = @events.where('state' => mystate.name)
        if events_mystate.count > 0
          @mystates << mystate
          events_mystate.each do |myevent|
            length += myevent.event_type.length
          end
          @eventstats["#{mystate.name}"] = { 'count' => events_mystate.count, 'length' => length }
        end
      end

      @event_types.each do |mytype|
        events_mytype = @events.where('event_type_id' => mytype.id)
        if events_mytype.count > 0
          @mytypes << mytype
        end
      end
      @mytypes.each do |mytype|
        @mystates.each do |mystate|
          events_mytype = @events.where('event_type_id' => mytype.id)
          events_mytype_mystate = events_mytype.where('state' => mystate.name)
          typelength = 0
          if events_mytype_mystate.count > 0
            events_mytype_mystate.each do |myevent|
              typelength += myevent.event_type.length
              @totallength += myevent.event_type.length
            end

            if @eventstats[mytype.title].nil?
              @eventstats[mytype.title] = { 'count' => events_mytype.count,
                                            'length' => events_mytype.count * mytype.length }
            end

            tmp = { "#{mystate.name}" => { 'type_state_count' => events_mytype_mystate.count,
                                           'type_state_length' => typelength } }
            @eventstats[mytype.title].merge!(tmp)
          end
        end
      end
      @eventstats['totallength'] = @totallength

      respond_to do |format|
        format.html
        # Explicity call #to_json to avoid the use of EventSerializer
        format.json { render json: Event.where(state: :confirmed, program: @program).to_json }
      end
    end

    def show
      @tracks = @program.tracks
      @event_types = @program.event_types
      @comments = @event.root_comments
      @comment_count = @event.comment_threads.count
      @ratings = @event.votes.includes(:user)
      @difficulty_levels = @program.difficulty_levels
    end

    def edit
      @event_types = @program.event_types
      @tracks = Track.all
      @comments = @event.root_comments
      @comment_count = @event.comment_threads.count
      @user = @event.submitter
      @url = admin_conference_program_event_path(@conference.short_title, @event)
    end

    def comment
      comment = Comment.new(comment_params)
      comment.commentable = @event
      comment.user_id = current_user.id
      comment.save!
      if !params[:parent].nil?
        comment.move_to_child_of(params[:parent])
      end

      redirect_to admin_conference_program_event_path(@conference.short_title, @event)
    end

    def update
      if @event.update_attributes(event_params)

        if request.xhr?
          render js: 'index'
        else
          flash[:notice] = "Successfully updated event with ID #{@event.id}."
          redirect_back_or_to(admin_conference_program_event_path(@conference.short_title, @event))
        end
      else
        @url = admin_conference_program_event_path(@conference.short_title, @event)
        flash[:notice] = 'Update not successful. ' + @event.errors.full_messages.to_sentence
        render :edit
      end
    end

    def create; end

    def accept
      send_mail = @event.program.conference.email_settings.send_on_accepted
      subject = @event.program.conference.email_settings.accepted_subject.blank?
      update_state(:accept, 'Event accepted!', true, subject, send_mail)
    end

    def confirm
      update_state(:confirm, 'Event confirmed!')
    end

    def cancel
      update_state(:cancel, 'Event canceled!')
    end

    def reject
      send_mail = @event.program.conference.email_settings.send_on_rejected
      subject = @event.program.conference.email_settings.rejected_subject.blank?
      update_state(:reject, 'Event rejected!', true, subject, send_mail)
    end

    def restart
      update_state(:restart, 'Review started!')
    end

    def vote
      @ratings = @event.votes.includes(:user)

      if (votes = current_user.votes.find_by_event_id(params[:id]))
        votes.update_attributes(rating: params[:rating])
      else
        @myvote = @event.votes.build
        @myvote.user = current_user
        @myvote.rating = params[:rating]
        @myvote.save
      end

      respond_to do |format|
        format.html { redirect_to admin_conference_program_event_path(@conference.short_title, @event) }
        format.js
      end
    end

    private

    def event_params
      params.require(:event).permit(
                                    # Set also in proposals controller
                                    :title, :subtitle, :event_type_id, :abstract, :description, :require_registration, :difficulty_level_id,
                                    # Set only in admin/events controller
                                    :track_id, :state, :language, :start_time, :is_highlight,
                                    # Not used anymore?
                                    :proposal_additional_speakers, :user, :users_attributes)
    end

    def comment_params
      #fixed issue #889
      params.require(:comment).permit(:commentable, :body, :user_id)
    end

    def get_event
      @event = @conference.program.events.find(params[:id])
      if !@event
        redirect_to admin_conference_program_events_path(conference_id: @conference.short_title),
                    error: 'Error! Could not find event!'
        return
      end
      @event
    end

    def update_state(transition, notice, mail = false, subject = false, send_mail = false)
      alert = @event.update_state(transition, mail, subject, send_mail, params[:send_mail].blank?)

      if alert.blank?
        flash[:notice] = notice
        redirect_back_or_to(admin_conference_program_events_path(conference_id: @conference.short_title)) && return
      else
        flash[:error] = alert
        return redirect_back_or_to(admin_conference_program_events_path(conference_id: @conference.short_title)) && return
      end
    end
  end
end

app/controllers/api/v1/events_controller.rb
module Api
  module V1
    class EventsController < Api::BaseController
      load_resource :conference, find_by: :short_title
      respond_to :json

      def index
        events = Event.includes(:conference, :track, :room, :event_type, event_users: :user)

        if @conference
          events = events.where(conference: @conference)
        end

        respond_with events.confirmed
      end
    end
  end
end

app/views/admin/events/_change_state_dropdown.html.haml
- if event.transition_possible? :accept
  %li= link_to 'Accept event',
  accept_admin_conference_program_event_path(@conference.short_title, event),
  method: :patch, id: "accept_event_#{event.id}"

  - if @conference.email_settings.send_on_accepted?
    %li= link_to 'Accept event (without email)',
    accept_admin_conference_program_event_path(@conference.short_title, event, send_mail: false),
    method: :patch, hint: 'Accept this event without sending an automated email.',
    id: "accept_event_without_mail_#{event.id}"

- if event.transition_possible? :reject
  %li= link_to 'Reject event',
  reject_admin_conference_program_event_path(@conference.short_title, event),
  method: :patch, confirm: 'Are you sure?', id: "reject_event_#{event.id}"

  - if @conference.email_settings.send_on_rejected?
    %li= link_to 'Reject event (without email)',
    reject_admin_conference_program_event_path(@conference.short_title, event, send_mail: false),
    method: :patch, confirm: 'Are you sure?', id: "reject_event_without_mail_#{event.id}"

- if event.transition_possible? :restart
  %li= link_to 'Start review',
  restart_admin_conference_program_event_path(@conference.short_title, event),
  method: :patch, id: "restart_event_#{event.id}"

- if event.transition_possible? :confirm
  %li= link_to 'Confirm event',
  confirm_admin_conference_program_event_path(@conference.short_title, event),
  method: :patch, id: "confirm_event_#{event.id}",
  hint: 'Confirm that the speaker(s) will be present and that the event will actually take place.'

- if event.transition_possible? :cancel
  %li= link_to 'Cancel event',
  cancel_admin_conference_program_event_path(@conference.short_title, event),
  method: :patch, id: "cancel_event_#{event.id}",
  hint: 'Mark this event as cancelled. Usually this means that the speakers had to cancel their appearance.'

app/views/admin/events/_nested_comments.html.haml
%div{style: "padding-left:#{padding}px"}
  .well.comment-section
    %strong= comment.user.name
    %i= comment.created_at
    %p.comment-body= comment.body
    %div
      %a.pull-right.comment-reply-link{href: "#"} Reply
      .comment-reply
        = semantic_form_for :comment, url:  "#{comment_admin_conference_program_event_path(@conference.short_title, comment.commentable_id)}", method: :post do |f|
          = f.input :body
          %input{name: "parent", type: "hidden", value: "#{comment.id}"}
          %input{name: "authenticity_token", type: "hidden", value: "#{form_authenticity_token}"}
          %button.btn.btn-primary.pull-right{name: "button", type: "submit"} Add Reply
  - comment.children.each do |child|
    = render "nested_comments", comment: child, padding: 50

app/views/admin/events/_proposal.html.haml
.row
  .col-md-12
    %h3
      = @event.title
      %br
      %small
        = @event.subtitle
      = link_to 'Edit', edit_admin_conference_program_event_path(@conference.short_title, @event), class: 'btn btn-mini btn-primary pull-right'

.row
  .col-md-12
    %table.table
      %tr
        %td.col-md-2
          %b Type
        %td
          .dropdown
            = link_to '#', class: 'dropdown-toggle', id: 'type-dropdown' do
              - if @event.event_type.nil?
                Event Type
              - else
                = @event.event_type.title
              <b class='caret'></b>
            %ul.dropdown-menu
              - @event_types.each do |type|
                %li= link_to type.title,
                admin_conference_program_event_path(@conference.short_title,
                                            @event,
                                            event: { event_type_id: type.id }),
                method: :patch
      %tr
        %td
          %b Highlight
        %td
          = check_box_tag @conference.short_title, @event.id, @event.is_highlight,
            method: :patch, url: "/admin/conference/#{@conference.short_title}/program/events/#{@event.id}?event[is_highlight]=",
            class: 'switch-checkbox', data: { size: 'small',
                                              off_color: 'warning',
                                              on_text: 'Yes',
                                              off_text: 'No' }

      %tr
        %td
          %b State
        %td
          .dropdown
            = link_to '#', class: 'dropdown-toggle' do
              = @event.state.humanize
              <b class='caret'></b>
            %ul.dropdown-menu
              = render 'change_state_dropdown', event: @event
      %tr
        %td
          %b Track
        %td
          .dropdown
            = link_to '#', class: 'dropdown-toggle', id: 'track-dropdown' do
              - if @event.track.nil?
                Track
              - else
                = @event.track.name
              <b class="caret"></b>
            %ul.dropdown-menu
              - @tracks.each do |track|
                %li= link_to track.name,
                admin_conference_program_event_path(@conference.short_title,
                                            @event,
                                            event: { track_id: track.id }),
                method: :patch
      %tr
        %td
          %b Difficulty
        %td
          .dropdown
            = link_to '#', class: 'dropdown-toggle', id: 'difficulty-dropdown' do
              - if @event.difficulty_level.nil?
                Difficulty Level
              - else
                = @event.difficulty_level.title
              <b class="caret"></b>
            %ul.dropdown-menu
              - @difficulty_levels.each do |difficulty|
                %li= link_to difficulty.title, admin_conference_program_event_path(@conference.short_title,
                                            @event,
                                            event: { difficulty_level_id: difficulty.id }),
                method: :patch
      %tr
        %td
          %b Requires Registration
        %td
          = check_box_tag @conference.short_title, @event.id, @event.require_registration,
            method: :patch, url: "/admin/conference/#{@conference.short_title}/program/events/#{@event.id}?event[require_registration]=",
            class: 'switch-checkbox', data: { size: 'small',
                                              off_color: 'warning',
                                              on_text: 'Yes',
                                              off_text: 'No' }

      - if !@event.room.nil?
        %tr
          %td
            %b Room
          %td
            = @event.room.name
      - if !@event.start_time.nil?
        %tr
          %td
            %b Scheduled time
          %td
            = @event.start_time
      %tr
        %td
          %b Submitter
        %td
          = link_to @event.submitter.name, admin_user_path(@event.submitter)
          (
          = link_to @event.submitter.email, "mailto: #{@event.submitter.email}"
          )
      %tr
        %td
          %b Biography
        %td
          = simple_format(@event.submitter.biography)
      %tr
        %td
          %b Submitted on
        %td= @event.created_at
      %tr
        %td
          %b Last updated on
        %td= @event.updated_at
      %tr
        %td
          %b Abstract
        %td= simple_format(@event.abstract)
      %tr
        %td
          %b Description
        %td= simple_format(@event.description)

      - if @conference.program && @conference.program.rating && @conference.program.rating > 0
        = render partial: 'voting'

.row
  = link_to "Comments (#{@comment_count})", '#', id: 'event-comment-link'
  #comments-div
    %hr
    %ul.media
      %div
        .row-fluid
          = semantic_form_for :comment, url: comment_admin_conference_program_event_path(@conference.short_title, @event.id), method: :post do |f|
            = f.input :body
            = f.submit 'Add Comment', class: 'btn btn-primary pull-right'
        %br
        %br
        - @comments.each do |comment|
          %div
            = render partial: 'nested_comments', locals: { comment: comment, padding: 0}

app/views/admin/events/_user_fields.html.haml
.nested-fields
  = f.inputs do
    = f.input :email
    = f.input :name
  = remove_association_link :user, f

app/views/admin/events/_voting.html.haml
%table.table#myrating
  %tr
    %td.col-md-2
      %b Rating
    %td
      - if @event.average_rating.to_f > 0
        #{@event.average_rating}/#{@conference.program.rating}
      - else
        Rating: 0/#{@conference.program.rating}

      - @conference.program.rating.times do |counter|
        - if @event.average_rating.to_f.round == counter+1
          = label_tag "label_rating", "", :class => "avgrating", :avgrate => true
          = javascript_tag "$('label[avgrate=true]').prevAll().andSelf().addClass('bright');"
        - else
          = label_tag "label_rating", "", :class => "avgrating"
  %tr
    %td
      %b Voters
    %td
      = @event.voters.length
      - if @event.voters.length > 0
        (
        = @ratings.map {|x| "#{x.name}"}.join ', '
        )
  %tr
    %td
      %b Your vote
    %td
      - @conference.program.rating.times do |counter|
        - voted = @event.voted?(@event, current_user)
        - if voted && voted.rating == counter+1
          = link_to "", vote_admin_conference_program_event_path(@conference.short_title, @event, :rating => counter+1), :remote => true, :id =>"label#{counter+1}", :class => "myrating", :voted => true
        - else
          = link_to "", vote_admin_conference_program_event_path(@conference.short_title, @event, :rating => counter+1), :remote => true, :id =>"label#{counter+1}", :class => "myrating"
      %br

  - if @ratings.length > 0
    - @ratings.each do |rate|
      - unless rate.user_id == current_user.id
        %tr
          %td
            = rate.name
          %td
            - @conference.program.rating.times do |counter|
              - voted = @event.voted?(@event, rate.user)
              - if voted && voted.rating == counter+1
                = label_tag "label#{counter+1}", "", :class => "othersrating", :voted => true
                = javascript_tag "$('label[voted=true]').prevAll().andSelf().addClass('bright');"
              - else
                = label_tag "label#{counter+1}", "", :class => "othersrating"
:javascript
  $(function () {
    var checkedId = $("a[voted='true']").attr('id');
    $('a[id=' + checkedId + ']').prevAll().andSelf().addClass('bright');
  });

  $(".myrating").hover(
    function() {    // mouseover
        $(this).prevAll().andSelf().addClass('glow');
    },
    function() {  // mouseout
        $(this).siblings().andSelf().removeClass('glow');
    }
  );

  $(".myrating").click(function() {
    $(this).siblings().removeClass("bright");
    $(this).prevAll().andSelf().addClass("bright");
  });

app/views/admin/events/edit.html.haml
= render 'proposal/form'

app/views/admin/events/index.html.haml
.row
  .col-md-12
    .page-header
      %h1
        Events
        - if @events.any?
          = "(#{@events.length})"
      %p.text-muted
        All the submissions of your speakers
.row
  .col-md-12
    %table.table.table-striped.table-bordered.table-hover.datatable
      %thead
        %th
          %b ID
        %th
          %b Title
        - if @program.rating_enabled?
          %th
            %b Rating
        %th
          %b Submitter
        %th
          %b Speaker
        %th
          %b Pre-registration
        %th
          %b Highlight
        %th
          %b Type
        %th
          %b Track
        %th
          %b Difficulty
        %th
          %b State
      - @events.each do |event|
        %tr
          %td
            = event.id
          %td
            =link_to event.title, admin_conference_program_event_path(@conference.short_title, event)

          - if @program.rating_enabled?
            %td.col-md-1{'data-order' => "#{event.average_rating}"}
              - if event.average_rating.to_f > 0
                #{event.average_rating}/#{@program.rating}
                %br
                #{pluralize(event.voters.length, 'voter')}
                %br
                - @program.rating.times do |counter|
                  - if event.average_rating.to_f.round == counter+1
                    = label_tag "label_rating", "", :class => "avgrating", :avgrate => true
                    = javascript_tag "$('label[avgrate=true]').prevAll().andSelf().addClass('bright');"
                  - else
                    = label_tag "label_rating", "", :class => "avgrating"
                %br
                - voted = event.voted?(event, current_user)
                - if voted
                  %span.label.label-success
                    Your rating: #{voted.rating}
                - else
                  %span.label.label-danger
                    Not rated
              - else
                0/#{@program.rating}
              %br

          - if event.submitter && event.submitter.registrations && event.submitter.registrations.count < 1
            - bgcolor="#F7819F"
          - else
            - bgcolor=""
          %td{:style=>"background-color: #{bgcolor}"}
            - if !event.submitter.nil?
              =link_to event.submitter.name, admin_user_path(event.submitter)
              - if event.submitter.registrations.count < 1
                (Unregistered!)
            - else
              Unknown submitter
          %td
            - if speaker = event.speakers.first
              = link_to speaker.name, admin_user_path(speaker)
            - else
              Unknown speaker

          %td{'data-order' => "#{event.require_registration}"}
            = check_box_tag @conference.short_title, event.id, event.require_registration,
              method: :patch, url: "/admin/conference/#{@conference.short_title}/program/events/#{event.id}?event[require_registration]=",
              class: 'switch-checkbox', data: { size: 'small',
                                                off_color: 'warning',
                                                on_text: 'Yes',
                                                off_text: 'No' }

          %td{'data-order' => "#{event.is_highlight}"}
            = check_box_tag @conference.short_title, event.id, event.is_highlight,
              method: :patch, url: "/admin/conference/#{@conference.short_title}/program/events/#{event.id}?event[is_highlight]=",
              class: 'switch-checkbox', data: { size: 'small',
                                                off_color: 'warning',
                                                on_text: 'Yes',
                                                off_text: 'No' }

          %td
            .btn-group
              %button{:type=>"button", :class=>"btn btn-link dropdown-toggle", "data-toggle"=>"dropdown"}
                - if event.event_type.nil?
                  Event Type
                - else
                  = event.event_type.title
                %span.caret
              %ul.dropdown-menu
                - @event_types.each do |type|
                  %li= link_to type.title,
                  admin_conference_program_event_path(@conference.short_title,
                                              event,
                                              event: { event_type_id: type.id }),
                  method: :patch
          %td
            .btn-group
              %button{:type=>"button", :class=>"btn btn-link dropdown-toggle", "data-toggle"=>"dropdown"}
                - if event.track.nil?
                  Track
                - else
                  = event.track.name
                %span.caret
              %ul.dropdown-menu
                - @tracks.each do |track|
                  %li= link_to track.name,
                  admin_conference_program_event_path(@conference.short_title,
                                              event,
                                              event: { track_id: track.id }),
                  method: :patch
          %td
            .btn-group
              %button{:type=>"button", :class=>"btn btn-link dropdown-toggle", "data-toggle"=>"dropdown"}
                - if event.difficulty_level.nil?
                  Difficulty
                - else
                  = event.difficulty_level.title
                %span.caret
              %ul.dropdown-menu
                - @difficulty_levels.each do |difficulty_level|
                  %li= link_to difficulty_level.title,
                  admin_conference_program_event_path(@conference.short_title,
                                              event,
                                              event: { difficulty_level_id: difficulty_level.id }),
                  method: :patch

          %td
            - if event.state == "withdrawn"
              Withdrawn
            - else
              .btn-group
                %button{:type=>"button", :class=>"btn btn-link dropdown-toggle", "data-toggle"=>"dropdown"}
                  = event.state.humanize
                  %span.caret
                %ul.dropdown-menu{:role=>"menu"}
                  = render 'change_state_dropdown', event: event

app/views/admin/events/show.html.haml
.tabbable
  %ul.nav.nav-tabs
    %li.active
      = link_to "Proposal", "#proposal-content", "data-toggle"=>"tab"
    %li
      = link_to "History", "#history-content", "data-toggle"=>"tab"
  .tab-content
    #proposal-content.tab-pane.active
      = render 'proposal'
    #history-content.tab-pane
      .col-md-12
        %table.table
          %thead
            %th
              %b Who
            %th
              %b Timestamp
            %th
              %b Modification Type
            %th
              %b Changes
          %tbody
          - @event.versions.each do |version|
            %tr
              %td
                - if !version.whodunnit.nil?
                  = User.find(version.whodunnit).name
                - else
                  No user (probably via the console)
              %td
                = version.created_at
              %td
                = version.event
              %td
                - version.changeset.each_key do |key|
                  = "#{key}: #{version.changeset[key][0]} -> #{version.changeset[key][1]}"
                  %br

app/views/admin/events/vote.js.erb
$('table#myrating').replaceWith("<%= escape_javascript(render :partial => 'voting') %>");